<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Orderattributes
 * @version    1.0.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $collection = $this->getAttributeCollection();?>
<?php if ($collection->getSize() > 0) : ?>
    <div id="aw-orderattributes-checkoutonestep-attributes-container-shipping-method">
        <ul class="form-list" >
            <?php foreach($collection as $attribute):?>
                <?php
                $html = $attribute->unpackData()->getTypeModel()->getFrontendFormRenderer()
                    ->setValue($this->getValueByAttributeId($attribute->getId()))
                    ->getHtml(true);
                ?>
                <?php if(strlen(trim($html)) > 0) :?>
                    <li class="fields">
                        <div class="aw-onestepcheckout-general-form-field aw-onestepcheckout-general-form-field-wide"><?php echo $html;?></div>
                    </li>
                <?php endif;?>
            <?php endforeach;?>
        </ul>
    </div>
<?php endif;?>