<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Orderattributes
 * @version    1.0.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><script type="text/javascript">
    //fix magento bug with time: Mage_Core_Block_Html_Date - line 54 & js/calendar/calendar.js - line 900
    if (typeof(Calendar) === 'function' && typeof(Calendar.setup) === 'function') {
        var awOASaveCalendarFN = Calendar.setup;
        Calendar.setup = function(calendarSetupObject) {
            if (typeof(calendarSetupObject) === 'object' && "showsTime" in calendarSetupObject) {
                if (calendarSetupObject.showsTime === "true") {
                    calendarSetupObject.showsTime = true;
                } else if (calendarSetupObject.showsTime === "false") {
                    calendarSetupObject.showsTime = false;
                }
            }
            awOASaveCalendarFN(calendarSetupObject);
        }
    }
</script>