<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Orderattributes
 * @version    1.0.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><script type="text/javascript">
Validation.add('aw-ca-validate-length', 'Text length does not satisfy specified text range.', function(v, elm){
    var reMax = new RegExp(/^maximum-length-[0-9]+$/);
    var reMin = new RegExp(/^minimum-length-[0-9]+$/);
    var result = true;
    $w(elm.className).each(function(name, index) {
        if (name.match(reMax) && result) {
            var length = name.split('-')[2];
            result = (v.length <= length);
        }
        if (name.match(reMin) && result && !Validation.get('IsEmpty').test(v)) {
            var length = name.split('-')[2];
            result = (v.length >= length);
        }
    });
    return result;
});
</script>