<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Storelocator
 * @version    1.1.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>

<tr><td colspan="2">&nbsp;</td></tr>
<tr>
    <td colspan="2">
        <div id="storelocator-messages" style="display:none"><ul class="messages"><li class="notice-msg"><ul><li><span><?php echo $this->__('Nothing Found'); ?></span></li></ul></li></ul></div>
        <div class="google-map" id="googlep-map">
            <div class="coords">
                <div id="search-location-block" class="search-location-block">
                    <?php echo $this->getFindLocationHtml(); ?>
                    <p class="note" id="search-location-note"><span><?php echo $this->__('Find store location according to entered country, city and street addraess'); ?></span></p>
                </div>
            </div> 
            <div id="google-map-contents" class="google-map-contents"></div>          
        </div>       
    </td>    
</tr>