<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Storelocator
 * @version    1.1.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><tr>
    <td class="label"><?php echo $this->getElement()->getLabel(); ?></td>     
    <td class="value">
          <select id="location_billing:region_id" name="state" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
             <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
          </select>
        <input type="text" id="location_billing:region" name="state" value="<?php echo $this->escapeHtml($this->getElement()->getState()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
    </td>   
</tr>