<?php
$field_id	 = $this->field['field_id'];
$field_title = $this->field['title'];
$hidden_field_value = $this->field['field_value'];
$required	 = $this->field['required'];
$field_class     = $this->field['field_class'];
$field_note	 = $this->field['field_note'];
$tooltip	 = $this->field['tooltip'];
if($required){
    $custom_message = $this->field['custom_validation'];
    $custom_class = ' required-entry-'.$this->field['field_id'];
    $required_class = (!empty($custom_message)) ? $custom_class : ' required-entry';
}
else
{
    $required_class='';
}
//To retrive field value on unsuccess submission
$field_value = Mage::helper('flexibleforms');
if($this->field['type']=='hidden'): ?>
        <input type="hidden" title="<?php echo $field_title; ?>" id="options_<?php echo $field_id; ?>" name="options[<?php echo $field_id; ?>]" value="<?php echo $hidden_field_value;?>" />
<?php endif;?>