<?php
$field_id	 = $this->field['field_id'];
$field_title     = $this->field['title'];
$required	 = $this->field['required'];
$field_class     = $this->field['field_class'];
$field_note	 = $this->field['field_note'];
$tooltip	 = $this->field['tooltip'];
if($required){
    $custom_message = $this->field['custom_validation'];
    $custom_class = ' required-entry-'.$this->field['field_id'];
    $required_class = (!empty($custom_message)) ? $custom_class : ' required-entry';
}
//To retrive field value on unsuccess submission
$field_value = Mage::helper('flexibleforms');

if($this->field['type']=='time'): ?>

    <label <?php echo $required ? ' class="required" ' : '' ?> for="options_<?php echo $field_id; ?>"><?php echo $this->__($field_title); ?> <?php echo $required ? ' <em>*</em> ' : '' ?></label>
    <?php if($tooltip): ?>
        <span id="label-info">
            <img src="<?php echo $this->getSkinUrl("css/flexibleforms/images/help.png"); ?>" alt="<?php echo $this->__('Help'); ?>" />
            <span class="label-info-tooltip"><?php echo $tooltip; ?></span>
        </span>
    <?php endif; ?>
    <div class="input-box">
        <?php /*
        <input type="text" class="input-text<?php echo $required_class ? $required_class : '' ?>" title="<?php echo $field_title; ?>" id="options_<?php echo $field_id; ?>" name="options[<?php echo $field_id; ?>]" value="<?php echo $field_value->getFieldValue($field_id);?>" />
         */ ?>

        <span class="time-picker">
            <select style="width:auto" title="" class="product-custom-option datetime-picker" id="options_<?php echo $field_id; ?>_hour" name="options[<?php echo $field_id; ?>][hour]">
                <option value="">-</option>
                <option value="01">01</option>
                <option value="02">02</option>
                <option value="03">03</option>
                <option value="04">04</option>
                <option value="05">05</option>
                <option value="06">06</option>
                <option value="07">07</option>
                <option value="08">08</option>
                <option value="09">09</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>&nbsp;<b>:</b>&nbsp;
            <select style="width:auto" title="" class="product-custom-option datetime-picker" id="options_<?php echo $field_id; ?>_minute" name="options[<?php echo $field_id; ?>][minute]">
                <option value="">-</option>
                <option value="00">00</option>
                <option value="01">01</option>
                <option value="02">02</option>
                <option value="03">03</option>
                <option value="04">04</option>
                <option value="05">05</option>
                <option value="06">06</option>
                <option value="07">07</option>
                <option value="08">08</option>
                <option value="09">09</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
                <option value="13">13</option>
                <option value="14">14</option>
                <option value="15">15</option>
                <option value="16">16</option>
                <option value="17">17</option>
                <option value="18">18</option>
                <option value="19">19</option>
                <option value="20">20</option>
                <option value="21">21</option>
                <option value="22">22</option>
                <option value="23">23</option>
                <option value="24">24</option>
                <option value="25">25</option>
                <option value="26">26</option>
                <option value="27">27</option>
                <option value="28">28</option>
                <option value="29">29</option>
                <option value="30">30</option>
                <option value="31">31</option>
                <option value="32">32</option>
                <option value="33">33</option>
                <option value="34">34</option>
                <option value="35">35</option>
                <option value="36">36</option>
                <option value="37">37</option>
                <option value="38">38</option>
                <option value="39">39</option>
                <option value="40">40</option>
                <option value="41">41</option>
                <option value="42">42</option>
                <option value="43">43</option>
                <option value="44">44</option>
                <option value="45">45</option>
                <option value="46">46</option>
                <option value="47">47</option>
                <option value="48">48</option>
                <option value="49">49</option>
                <option value="50">50</option>
                <option value="51">51</option>
                <option value="52">52</option>
                <option value="53">53</option>
                <option value="54">54</option>
                <option value="55">55</option>
                <option value="56">56</option>
                <option value="57">57</option>
                <option value="58">58</option>
                <option value="59">59</option>
            </select>&nbsp;
            <select style="width:auto" title="" class="product-custom-option datetime-picker" id="options_<?php echo $field_id; ?>_day_part" name="options[<?php echo $field_id; ?>][day_part]">
                <option value="AM">AM</option>
                <option value="PM">PM</option>
            </select>
        </span>
        <input type="hidden" value="" class="validate-datetime-<?php echo $field_id; ?>" name="validate_datetime_<?php echo $field_id; ?>" id="options_<?php echo $field_id; ?>">

        <?php if($field_note): ?>
            <p class="note"><?php echo $field_note; ?></p>
        <?php endif; ?>
    </div>

    <script type="text/javascript">
    //<![CDATA[
        Validation.addAllThese(
        [
            ['validate-datetime-<?php echo $field_id; ?>', 'This is a required option.', function(v) {
                var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $field_id; ?>"]');
                for (var i=0; i < dateTimeParts.length; i++) {
                    if (dateTimeParts[i].value == "") return false;
                }
                return true;
             }]
        ]
        );
    //]]>
    </script>
    
<?php endif; ?>