<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Orderattributes
 * @version    1.0.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><script type="text/javascript">
    var optionDefaultInputType = null;
    switchFieldsVisibility()
    if($('type')) {
        Event.observe($('type'), 'change', switchFieldsVisibility);
    }

    function switchFieldsVisibility()
    {
        checkOptionsPanelVisibility();
        hideAllSpecifiedFields();
        if (!$('type')) {
            return;
        }
        var currentValue = $('type').getValue();

        switch (currentValue) {
            case 'text':
                setRowVisibility('default_value_text', true);
                setRowVisibility('minimum_text_length', true);
                setRowVisibility('maximum_text_length', true);
                setRowVisibility('input_validation', true);
                break;
            case 'textarea':
                setRowVisibility('default_value_textarea', true);
                setRowVisibility('minimum_text_length', true);
                setRowVisibility('maximum_text_length', true);
                break;
            case 'date':
                setRowVisibility('default_value_date', true);
                break;
            case 'yesno':
                setRowVisibility('default_value_yesno', true);
                break;
            case 'multipleselect':
                optionDefaultInputType = 'checkbox';
                break;
            case 'dropdown':
                optionDefaultInputType = 'radio';
                break;
            default:
                break;
        }

        var elems = document.getElementsByName('default[]');
        for (var i = 0; i < elems.length; i++) {
            elems[i].type = optionDefaultInputType;
        }
    }

    function hideAllSpecifiedFields() {
        setRowVisibility('default_value_text', false);
        setRowVisibility('default_value_textarea', false);
        setRowVisibility('default_value_date', false);
        setRowVisibility('default_value_yesno', false);
        setRowVisibility('minimum_text_length', false);
        setRowVisibility('maximum_text_length', false);
        setRowVisibility('input_validation', false);
    }

    function setRowVisibility(id, isVisible)
    {
        if ($(id)) {
            var tr = $(id).up(1);
            if (isVisible) {
                tr.show();
            } else {
                tr.hide();
            }
        }
    }

    function checkOptionsPanelVisibility(){
        if($('matage-options-panel')){
            var panel = $('matage-options-panel');
            if($('type') && ($('type').value=='dropdown' || $('type').value == 'multipleselect')){
                panel.show();
            }
            else {
                panel.hide();
            }
        }
    }

    function updateRequriedOptions() {
        if ($F('type')=='dropdown' && $F('is_required')==1) {
            $('option-count-check').addClassName('required-options-count');
        } else {
            $('option-count-check').removeClassName('required-options-count');
        }
    }
    if($('type')){
        Event.observe($('type'), 'change', updateRequriedOptions);
    }
    if ($('is_required')) {
        Event.observe($('is_required'), 'change', updateRequriedOptions);
    }
    updateRequriedOptions();
</script>